# --- Global Configs ---
queue_size: 1

rate: 10

# --- Sail Configs ---
sail_limits: 80 #1.3962634  # 80 degree
sail_servo_scalar: 20.25
sail_setpoint: 5
max_roll: 30 #0.52359877559 # pi/6

# --- Rudder Configs ---
rudder_limits: 45 #0.7853981633974483  # pi/4 radians
pid_coefficients:
    kp: 1
    ki: 0.1
    kd: 0.05
rudder_upper_threshold: 1.5
rudder_lower_threshold: 0.5